
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 10
      max-active: 100
      min-evictable-idle-time-millis: 30000
    redis:
      host: localhost
      port: 6379
      password:
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates
    suffix: .html
  mail:
    host: smtp.qq.com
    port: 587
    username: 邮箱
    password: 密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
#          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      group-id: forum-comsumer-group
      auto-commit-interval: 3000
  data:
    elasticsearch:
      cluster-name: guangke
      cluster-nodes: localhost:9300
  task:
    #Spring TaskExecution线程池
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    #Spring TaskScheduling线程池
    scheduling:
      pool:
        size: 5
  #不从内存读取任务，而是从数据库
  quartz:
    job-store-type: jdbc
    scheduler-name: forumScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            isClustered: true
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 5

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guangke.forum.pojo
#  messages:
#    basename: i18n.login
#  servlet:
#    multipart:
#      max-file-size: 5MB #单个文件大小限制
#      max-request-size: 10MB #总上传文件大小限制
#  jpa:
#    show-sql: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
server:
  port: 8080
  servlet:
    context-path: #/forum
forum:
  path:
    domain: http://47.107.191.121 #访问nginx的80端口，反向代理到8080
    #头像上传的本地路径
    uploadImage: /tmp/uploads

wk:
  cmd: /opt/wkhtmltoimage.sh
  images:
    storage: /tmp/wk-images
qiniu:
  key:
    access:
    secret:
  bucket:
    header:
      name: forumheader
      url: http://qkdtgi43e.hn-bkt.clouddn.com
    share:
      name: forumshare
      url: http://qkdtajpjc.hn-bkt.clouddn.com
#caffeine缓存配置
#缓存热帖数据15页
caffeine:
  posts:
    max-size: 15
    #缓存180秒清除
    expired-seconds: 180
#actuator配置
management:
  endpoints:
    web:
      exposure:
        include: beans

